print("-----------a---------");
var a = db.overdue.aggregate([{$group: {_id: '$a'} }],{allowDiskUse: true} );
a.forEach(printjson);
print("-----------b---------");
var b = db.overdue.aggregate([{$group: {_id: '$b'} }],{allowDiskUse: true});
b.forEach(printjson);
print("-----------c---------");
var c = db.overdue.aggregate([{$group: {_id: '$c'} }],{allowDiskUse: true});
c.forEach(printjson);
print("-----------d---------");
var d = db.overdue.aggregate([{$group: {_id: '$d'} }],{allowDiskUse: true});
d.forEach(printjson);
print("-----------e---------");
var e = db.overdue.aggregate([{$group: {_id: '$e'} }],{allowDiskUse: true});
e.forEach(printjson);
print("-----------f---------");
var f = db.overdue.aggregate([{$group: {_id: '$f'} }],{allowDiskUse: true});
f.forEach(printjson);
print("-----------g---------");
var g = db.overdue.aggregate([{$group: {_id: '$g'} }],{allowDiskUse: true});
g.forEach(printjson);
print("-----------h---------");
var h = db.overdue.aggregate([{$group: {_id: '$h'} }],{allowDiskUse: true});
h.forEach(printjson);
print("-----------i---------");
var i = db.overdue.aggregate([{$group: {_id: '$i'} }],{allowDiskUse: true});
i.forEach(printjson);
print("-----------j---------");
var j = db.overdue.aggregate([{$group: {_id: '$j'} }],{allowDiskUse: true});
j.forEach(printjson);
print("-----------k---------");
var k = db.overdue.aggregate([{$group: {_id: '$k'} }],{allowDiskUse: true});
k.forEach(printjson);
print("-----------l---------");
var l = db.overdue.aggregate([{$group: {_id: '$l'} }],{allowDiskUse: true});
l.forEach(printjson);
print("-----------m---------");
var m = db.overdue.aggregate([{$group: {_id: '$m'} }],{allowDiskUse: true});
m.forEach(printjson);
print("-----------n---------");
var n = db.overdue.aggregate([{$group: {_id: '$n'} }],{allowDiskUse: true});
n.forEach(printjson);
print("-----------o---------");
var o = db.overdue.aggregate([{$group: {_id: '$o'} }],{allowDiskUse: true});
o.forEach(printjson);
print("-----------p---------");
var p = db.overdue.aggregate([{$group: {_id: '$p'} }],{allowDiskUse: true});
p.forEach(printjson);
print("-----------q---------");
var q = db.overdue.aggregate([{$group: {_id: '$q'} }],{allowDiskUse: true});
q.forEach(printjson);
print("-----------r---------");
var r = db.overdue.aggregate([{$group: {_id: '$r'} }],{allowDiskUse: true});
r.forEach(printjson);
print("-----------s---------");
var s = db.overdue.aggregate([{$group: {_id: '$s'} }],{allowDiskUse: true});
s.forEach(printjson);
print("-----------t---------");
var t = db.overdue.aggregate([{$group: {_id: '$t'} }],{allowDiskUse: true});
t.forEach(printjson);
print("-----------u---------");
var u = db.overdue.aggregate([{$group: {_id: '$u'} }],{allowDiskUse: true});
u.forEach(printjson);
print("-----------v---------");
var v = db.overdue.aggregate([{$group: {_id: '$v'} }],{allowDiskUse: true});
v.forEach(printjson);
print("-----------w---------");
var w = db.overdue.aggregate([{$group: {_id: '$w'} }],{allowDiskUse: true});
w.forEach(printjson);
print("-----------x---------");
var x = db.overdue.aggregate([{$group: {_id: '$x'} }],{allowDiskUse: true});
x.forEach(printjson);
print("-----------y---------");
var y = db.overdue.aggregate([{$group: {_id: '$y'} }],{allowDiskUse: true});
y.forEach(printjson);
print("-----------z---------");
var z = db.overdue.aggregate([{$group: {_id: '$z'} }],{allowDiskUse: true});
z.forEach(printjson);

//db.overdue.distinct('a').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('b').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('c').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('d').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('e').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('f').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('g').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('h').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('i').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('j').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('k').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('l').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('m').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('n').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('o').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('p').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('q').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('r').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('s').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('t').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('u').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('v').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('w').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('x').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('y').limit(1000).forEach(printjson);
//print("--------------------");
//db.overdue.distinct('z').limit(1000).forEach(printjson);
