#SELECT DISTINCT columnName FROM tableName; -- 去重
#SELECT columnName FROM tableName GROUP BY columnName; -- 分组

#SELECT * FROM query_result WHERE name REGEXP '[0-9]+'; -- 正则匹配
#SELECT * FROM query_result WHERE id_card NOT REGEXP '[0-9]+[xX]*'; -- 正则不匹配

#SELECT distinct(columnName) FROM tableName WHERE columnName REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' into outfile '/data/mysql/query_log_his1.txt'; -- 正则匹配json
#SELECT distinct(columnName) FROM tableName WHERE columnName NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' into outfile '/data/mysql/query_log_his2.txt'; -- 正则不匹配json

SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 94 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex94.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 95 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex95.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 96 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex96.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 97 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex97.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 98 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex98.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 99 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex99.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 100 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex100.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 101 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex101.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 102 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex102.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 103 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex103.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 104 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex104.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 105 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex105.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 106 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex106.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 107 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex107.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 108 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex108.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 109 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex109.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 110 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex110.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 111 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex111.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 112 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex112.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 113 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex113.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 114 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex114.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 115 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex115.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 116 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex116.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 118 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex117.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 119 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex118.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 120 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex119.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 121 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex120.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 122 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex121.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 123 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex122.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 124 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex123.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 125 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex124.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 126 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex125.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 127 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex126.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 128 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex127.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 129 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex128.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 130 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex129.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 131 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex130.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 117 AND service.app_id = q.appid AND q.data_txt REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' LIMIT 10 INTO OUTFILE '/data/mysql/output/query_log_his_regex131.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 94 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex94.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 96 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex95.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 95 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex96.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 97 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex97.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 98 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex98.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 99 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex99.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 100 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex100.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 101 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex101.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 102 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex102.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 103 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex103.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 104 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex104.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 105 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex105.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 106 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex106.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 107 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex107.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 108 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex108.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 109 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex109.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 110 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex110.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 111 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex111.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 112 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex112.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 113 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex113.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 114 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex114.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 115 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex115.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 116 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex116.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 117 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex117.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 118 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex118.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 119 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex119.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 120 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex120.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 121 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex121.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 122 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex122.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 123 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex123.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 124 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex124.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 125 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex125.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 126 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex126.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 127 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex127.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 128 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex128.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 129 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex129.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 130 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex130.txt';
SELECT DISTINCT q.data_txt FROM service, query_log_his q WHERE service.base_service_id = 131 AND service.app_id = q.appid AND q.data_txt NOT REGEXP '(\"([^,^\"]+)\":\"([^:^\"]+)\")|(\"([^,^\"]+)\":([\\d]+))' INTO OUTFILE '/data/mysql/output/query_log_his_notregex131.txt';
